apiVersion: v1
kind: Service
metadata:
  name: static-web
  labels:
    app: static-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
